apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: microservices
  namespace: default
  # see: https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.allow-http: "true"
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /go
        backend:
          serviceName: ms-go-hello
          servicePort: 3737
      - path: /node
        backend:
          serviceName: ms-node-hello
          servicePort: 3000

# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: tcp-services
#   namespace: ingress-nginx
# data:
#   9909: "default/ms-go-hello:3737"
